export const propertyTypes = [
  'AGRICULTURAL (NEC)',
  'APARTMENT',
  'CABIN',
  'CLUB',
  'COMMERCIAL (NEC)',
  'COMMERCIAL BUILDING',
  'COMMERCIAL CONDOMINIUM',
  'COMMON AREA',
  'CONDOMINIUM',
  'CONVERTED RESIDENCE',
  'COUNTY PROPERTY',
  'DUPLEX',
  'FARMS',
  'FAST FOOD FRANCHISE',
  'FEDERAL PROPERTY',
  'FOREST',
  'GROUP QUARTERS',
  'INDUSTRIAL (NEC)',
  'INDUSTRIAL PLANT',
  'MANUFACTURED HOME',
  'MARINA FACILITY',
  'MISCELLANEOUS',
  'MOBILE HOME',
  'MOBILE HOME LOT',
  'MOBILE HOME PARK',
  'MULTI FAMILY DWELLING',
  'NURSERY/HORTICULTURE',
  'OFFICE BUILDING',
  'PUBLIC (NEC)',
  'RELIGIOUS',
  'RESIDENTIAL (NEC)',
  'RESIDENTIAL ACREAGE',
  'RESIDENTIAL LOT',
  'RETAIL TRADE',
  'SFR',
  'STATE PROPERTY',
  'STORES & OFFICES',
  'STORES & RESIDENTIAL',
  'TAX EXEMPT',
  'TOWNHOUSE/ROWHOUSE',
  'TRIPLEX',
  'UTILITIES',
  'VACANT LAND (NEC)',
]

export const mockLocations = [
  {
    id: 1,
    name: 'Golden Gate Bridge',
    description: 'Iconic suspension bridge in San Francisco',
    lat: 37.8199,
    lng: -122.4783,
    type: 'landmark',
  },
  {
    id: 2,
    name: 'Central Park',
    description: 'Urban park in New York City',
    lat: 40.7829,
    lng: -73.9654,
    type: 'park',
  },
  {
    id: 3,
    name: 'Grand Canyon',
    description: 'Steep-sided canyon carved by the Colorado River',
    lat: 36.0544,
    lng: -112.1401,
    type: 'natural',
  },
]
