export const mockCompanyData = {
  domain: 'airbnb.com',
  company_name: 'Airbnb',
  description:
    'Airbnb is a company that provides a wide array of accommodations for every type of traveler. With over 7 million vacation rentals and 2 million top-rated guest favorites across more than 220 countries and regions, Airbnb offers a unique and diverse selection of stays worldwide.',
  logo: 'https://logo.abstractapi.com/cb6281618-c67a-5004-9c9b-29fc2245a4f7_-airbnb.png',
  year_founded: '2008',
  street_address: '888 Brannan Street',
  city: 'San Francisco',
  state: 'California',
  country: 'United States',
  postal_code: '94103',
  industry: 'Travel Services',
  employee_count: 6907,
  employee_range: '5K-10K',
  annual_revenue: '9917000000',
  revenue_range: '$1B-$10B',
  phone_numbers: ['+14155104027'],
  email_addresses: ['support@airbnb.com'],
  type: 'public',
  ticker: 'ABNB',
  exchange: 'XNAS',
  tags: ['Hospitality', 'Travel'],
  linkedin_url: 'linkedin.com/company/airbnb',
  facebook_url: 'facebook.com/airbnb',
  twitter_url: 'twitter.com/airbnb',
}
