export const propertyData = {
  status: {},
  property: [
    {
      identifier: {},
      lot: {
        lotNum: '31,32',
        lotSize1: 0.1076676,
        lotSize2: 4690,
        zoningType: 'Residential',
        siteZoningIdent: 'U-SU-C1',
        poolType: 'NO POOL',
      },
      area: {
        blockNum: '36',
        locType: 'VIEW - NONE',
        countrySecSubd: 'Denver',
        countyUse1: '113  ',
        munCode: 'DE',
        munName: 'DENVER',
        srvyRange: '68W',
        srvySection: '19',
        srvyTownship: '03S',
        subdName: 'BERKELEY',
        taxCodeArea: 'DENV',
        censusTractIdent: '102',
        censusBlockGroup: '3',
      },
      address: {
        country: 'US',
        countrySubd: 'CO',
        line1: '4529 WINONA CT',
        line2: 'DENVER, CO 80212',
        locality: 'DENVER',
        matchCode: 'ExaStr',
        oneLine: '4529 WINONA CT, DENVER, CO 80212',
        postal1: '80212',
        postal2: '2512',
        postal3: 'C037',
        stateFips: '08',
        situsHouseNumber: '4529',
        situsStreetName: 'WINONA',
        situsAddressSuffix: 'CT',
      },
      summary: {
        archStyle: 'OTHER',
        absenteeInd: 'OWNER OCCUPIED',
        propClass: 'Single Family Residence / Townhouse',
        propSubType: 'Residential',
        propType: 'SFR',
        propertyType: 'SINGLE FAMILY RESIDENCE',
        yearBuilt: 1900,
        propLandUse: 'SFR',
        propIndicator: 10,
        legal1: 'BERKELEY B36 L31 & S/2 OF L32 EXC REAR 8FT TO CITY',
        quitClaimFlag: 'False',
        REOflag: 'False',
      },
      utilities: {
        heatingFuel: 'GAS',
        heatingType: 'CENTRAL',
      },
      sale: {
        sequenceSaleHistory: 1,
        sellerName: 'MICHAEL S MATTICE',
        saleSearchDate: '2023-10-23',
        saleTransDate: '2023-10-20',
        transactionIdent: '1020620668',
        amount: {
          saleAmt: 710000,
          saleCode: 'SALE PRICE (FULL) Full sales price as per documents',
          saleRecDate: '2023-10-23',
          saleDisclosureType: 0,
          saleDocNum: '0000101441',
          saleTransType: 'Resale',
        },
        calculation: {
          pricePerBed: 355000,
          pricePerSizeUnit: 760.17,
        },
      },
      building: {
        size: {
          bldgSize: 934,
          grossSize: 1414,
          grossSizeAdjusted: 934,
          groundFloorSize: 934,
          livingSize: 934,
          sizeInd: 'LIVING SQFT',
          universalSize: 934,
        },
        rooms: {
          bathFixtures: 5,
          bathsFull: 1,
          bathsTotal: 1,
          beds: 2,
          roomsTotal: 5,
        },
        interior: {
          bsmtSize: 480,
          bsmtFinishedPercent: 0,
          fplcCount: 1,
          fplcInd: 'Y',
          fplcType: 'YES',
        },
        construction: {
          condition: 'GOOD',
          wallType: 'BRICK',
          propertyStructureMajorImprovementsYear: '2014',
        },
        parking: {
          garageType: 'Garage, Detached',
          prkgSize: 240,
          prkgType: 'Garage, Detached',
        },
        summary: {
          levels: 1,
          unitsCount: 1,
          view: 'VIEW - NONE',
          viewCode: '000',
        },
      },
      assessment: {
        appraised: {},
        assessed: {
          assdImprValue: 16850,
          assdLandValue: 23920,
          assdTtlValue: 40770,
        },
        market: {
          mktImprValue: 251500,
          mktLandValue: 412000,
          mktTtlValue: 663500,
        },
        tax: {
          taxAmt: 3229.06,
          taxPerSizeUnit: 3.46,
          taxYear: 2024,
          exemption: {},
          exemptiontype: {},
        },
        improvementPercent: 41,
        owner: {
          corporateIndicator: 'N',
          type: 'INDIVIDUAL',
          description: 'INDIVIDUAL',
          owner1: {
            fullName: 'JENNIFER NICOLE GUBNER',
            lastName: 'GUBNER ',
            firstNameAndMi: 'JENNIFER NICOLE',
          },
          owner2: {},
          owner3: {
            fullName: 'SYBNEY FRANCES STENTO',
            lastName: 'STENTO ',
            firstNameAndMi: 'SYBNEY FRANCES',
          },
          owner4: {},
          absenteeOwnerStatus: 'O',
          mailingAddressOneLine: '4529 WINONA CT, DENVER, CO 80212-2512',
        },
        mortgage: {
          FirstConcurrent: {
            trustDeedDocumentNumber: '0000101442',
            ident: '2023101442',
            amount: 510000,
            lenderLastName: 'THE HORN FUNDING CORP',
            companyCode: '8661',
            date: '2023-10-23',
            loanTypeCode: 'CNV',
            deedType: 'WD',
            term: '301',
            dueDate: '2048-11-01',
          },
          SecondConcurrent: {
            amount: 0,
            companyCode: '-1',
          },
          title: {
            companyName: 'GUARDIAN TITLE',
          },
        },
      },
      vintage: {
        lastModified: '2025-03-18',
        pubDate: '2025-03-18',
      },
    },
  ],
}
